base_model:
  type: 2
  range: ['/app/src/consumer/trans-h.h5']
debug: 0
loss_metric: 'mse'
arch: 'trans-h'
use25only: False
skip_load: True
re: 'fedAvg-h'
lstm_u: [30,45]
conv1d_ks: [6,20]
conv1d_f: [6,30]
dense_u: [10,15]
nheads: [1,3]
vdim: [10,20]
kdim: [5,10]
tr_do: [0, 1]
dropout_r: [2, 6]
optimizer: 'adam'
nexp: 10
direction_min: 1
validation_split: 0.2
dropout_39_exp:
  type: 1
  range: [.3,.7]
conv1d_17_exp:
  type: 0
  range: [16,64]

chunk_size: 196
epochs:
  type: 0
  range: [3,12]
C: .8
lr: 
  type: 1
  range: [0.0005, 0.001]
ntest: 3
patience: 10
batch_size: 70
l_s: 
  type: 0
  range: [200,300]
npreds: 10
window_size: 30
smoothing_perc: 0.05
error_buffer: 100
p: 0.13
