base_model:
  type: 2
  range: ['/app/src/consumer/basecnnlstm25.h5']
debug: 0
loss_metric: 'mse'
arch: 'cnnlstm25'
re: 'fedAvg'
optimizer: 'adam'
nexp: 10
direction_min: 1
validation_split: 0.2
dropout_39_exp:
  type: 1
  range: [.3,.7]
conv1d_17_exp:
  type: 0
  range: [16,64]

chunk_size: 196
epochs:
  type: 0
  range: [3,12]
C: 
  type: 1
  range: [.25, .9]
lr: 
  type: 1
  range: [0.0005, 0.002]
ntest: 3
patience: 3
batch_size: 70
l_s: 
  type: 0
  range: [200,300]
npreds: 10
window_size: 30
smoothing_perc: 0.05
error_buffer: 100
p: 0.13
