base_model: '/app/src/consumer/base-25.h5'
debug: 0
loss_metric: 'mse'
arch: 'lstm'
re: 'fedAvg'
optimizer: 'adam'
nexp: 10
direction_min: 1
validation_split: 0.2
dropout:
  type: 1
  range: [.1,.6]
lstm_batch_size:
  type: 0
  range: [35,100]
chunk_size: 196
epochs:
  type: 0
  range: [2,10]
C: 
  type: 1
  range: [.5, 1.]
lr: 
  type: 1
  range: [0.0005, 0.002]
ntest: 3
patience: 3
batch_size: 70
l_s: 
  type: 0
  range: [200,300]
npreds: 10
window_size: 30
smoothing_perc: 0.05
error_buffer: 100
p: 0.13
