loss_metric: 'mse'
arch: 'lstm'
re: 'fedSgd'
optimizer: 'adam'
validation_split: 0.2
dropout: 0.3
lstm_batch_size: 64
chunk_size: 196
epochs: 8
C: 0.7
lr: 0.001
ntest: 3
patience: 100
batch_size: 70
l_s: 250
npreds: 10
window_size: 30
smoothing_perc: 0.05
error_buffer: 100
p: 0.13