FROM python:3.8-slim-buster
RUN mkdir -p app/shared

WORKDIR /app
COPY shared/requirements.txt shared/
RUN ls shared/
RUN pip install -r shared/requirements.txt

EXPOSE 3001
CMD ["python","/app/src/publisher/pub.py"]
