apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q=
  RABBIT_PASSWORD: Z3Vlc3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cons1
  labels:
    app: cons1
spec:
  selector:
    matchLabels:
      app: cons1
  replicas: 1
  template:
    metadata:
      labels:
        app: cons1
    spec:
      containers:
      - name: rabbitmq-consumer
        image: cons1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: "N_ORBITERS_INT"
          value: "3"
        - name: "EXP_ID_INT"
          value: "0"
        - name: RABBIT_HOST
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-consumer
              key: RABBIT_USERNAME
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-consumer
              key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer
  labels:
    app: rabbitmq-consumer
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq-consumer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
