apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: viz
        image: viz
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: test-viz
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000