apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-publisher
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q=
  RABBIT_PASSWORD: Z3Vlc3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub3
  labels:
    app: pub3
spec:
  selector:
    matchLabels:
      app: pub3
  replicas: 15
  template:
    metadata:
      labels:
        app: pub3
    spec:
      containers:
      - name: rabbitmq-publisher
        image: pub3
        imagePullPolicy: Never
        volumeMounts:
        - name: hostvol1
          mountPath: /app/data
        - name: hostvol2
          mountPath: /app/src
        ports:
        - containerPort: 80
        env:
        - name: RABBIT_HOST 
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-publisher
              key: RABBIT_USERNAME
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-publisher
              key: RABBIT_PASSWORD
      volumes:
      - name: hostvol1
        hostPath:
          path: /home/docker/dummy
      - name: hostvol2
        hostPath:
          path: /home/docker/src
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher
  labels:
    app: rabbitmq-publisher
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq-publisher
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
